# Generated by Django 5.2.17 on 2026-08-19 12:27

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=64, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("municipality", "Municipality"),
                            ("city", "City"),
                            ("county", "County"),
                            ("region", "Region"),
                        ],
                        default="municipality",
                        max_length=32,
                    ),
                ),
                ("gnis", models.CharField(blank=True, db_index=True, max_length=64)),
                ("mun_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("seeded_from_gnis", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("state__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="SourceImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("sheet", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("imported_by", models.CharField(blank=True, max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-imported_at",),
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField()),
                ("label", models.CharField(db_index=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical collection",
                "verbose_name_plural": "historical collections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                ("domain", models.CharField(blank=True, db_index=True, max_length=255)),
                ("identity_key", models.CharField(max_length=500, unique=True)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("county", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operating", "Operating"),
                            ("closed", "Closed"),
                            ("merged", "Merged into another outlet"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="operating",
                        max_length=16,
                    ),
                ),
                ("founded", models.DateField(blank=True, null=True)),
                ("founded_raw", models.CharField(blank=True, max_length=64)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("closed_date_raw", models.CharField(blank=True, max_length=64)),
                ("newsbank_availability", models.CharField(blank=True, max_length=128)),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "source_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                ("review_note", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="outlets", to="directory.category"
                    ),
                ),
                (
                    "medium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outlets",
                        to="directory.medium",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlets",
                    models.ManyToManyField(
                        blank=True, related_name="collections", to="directory.outlet"
                    ),
                ),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "match_key",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("ownership_type", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsidiaries",
                        to="directory.owner",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="outlet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outlets",
                to="directory.owner",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOwner",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "match_key",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                ("ownership_type", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical owner",
                "verbose_name_plural": "historical owners",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OutletPlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asserted_by",
                    models.CharField(blank=True, help_text="source file or person", max_length=255),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("gnis", "GNIS id in the source"),
                            ("name", "Matched on place name and state"),
                            ("manual", "Set by an editor"),
                        ],
                        default="name",
                        max_length=16,
                    ),
                ),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_links",
                        to="directory.outlet",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_links",
                        to="directory.place",
                    ),
                ),
                (
                    "source_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place_links",
                        to="directory.sourceimport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="outlet",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                related_name="outlets",
                through="directory.OutletPlace",
                to="directory.place",
            ),
        ),
        migrations.CreateModel(
            name="CoverageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_file", models.CharField(db_index=True, max_length=255)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
                ("outlet_name_raw", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("medium_raw", models.CharField(blank=True, max_length=255)),
                ("state_raw", models.CharField(blank=True, max_length=128)),
                ("county", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("mun_id", models.CharField(blank=True, max_length=64)),
                ("gnis", models.CharField(blank=True, max_length=64)),
                ("domains_set_length", models.FloatField(blank=True, null=True)),
                ("article_length", models.FloatField(blank=True, null=True)),
                ("ownership", models.CharField(blank=True, max_length=255)),
                ("ownership_type", models.CharField(blank=True, max_length=128)),
                ("founded", models.CharField(blank=True, max_length=32)),
                ("closed_date", models.CharField(blank=True, max_length=32)),
                ("updated_on", models.CharField(blank=True, max_length=32)),
                ("newsbank_availability", models.CharField(blank=True, max_length=128)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage",
                        to="directory.outlet",
                    ),
                ),
                (
                    "source_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="directory.sourceimport",
                    ),
                ),
            ],
            options={
                "ordering": ("source_file", "outlet_name_raw"),
            },
        ),
        migrations.AddField(
            model_name="place",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="places",
                to="directory.state",
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outlets",
                to="directory.state",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOutlet",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                ("domain", models.CharField(blank=True, db_index=True, max_length=255)),
                ("identity_key", models.CharField(db_index=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("county", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operating", "Operating"),
                            ("closed", "Closed"),
                            ("merged", "Merged into another outlet"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="operating",
                        max_length=16,
                    ),
                ),
                ("founded", models.DateField(blank=True, null=True)),
                ("founded_raw", models.CharField(blank=True, max_length=64)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("closed_date_raw", models.CharField(blank=True, max_length=64)),
                ("newsbank_availability", models.CharField(blank=True, max_length=128)),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "source_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                ("review_note", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medium",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.medium",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.owner",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="directory.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical outlet",
                "verbose_name_plural": "historical outlets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="outletplace",
            index=models.Index(
                fields=["needs_review", "match_method"],
                name="directory_o_needs_r_14731b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="outletplace",
            constraint=models.UniqueConstraint(fields=("outlet", "place"), name="uq_outlet_place"),
        ),
        migrations.AddIndex(
            model_name="coveragerecord",
            index=models.Index(
                fields=["outlet", "source_file"], name="directory_c_outlet__5e8a13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coveragerecord",
            index=models.Index(fields=["outlet_name_raw"], name="directory_c_outlet__1de88a_idx"),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("name", "kind", "state"), name="uq_place_name_kind_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gnis", ""), _negated=True),
                fields=("gnis",),
                name="uq_place_gnis",
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(
                fields=["is_published", "name"], name="directory_o_is_publ_311d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(
                fields=["needs_review", "record_count"],
                name="directory_o_needs_r_dcceed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outlet",
            index=models.Index(fields=["status", "name"], name="directory_o_status_d545a5_idx"),
        ),
    ]
