# Generated by Django 5.2.17 on 2026-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragerecord",
            name="legacy_outlet_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
