# Generated by Django 5.2.17 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0002_coveragerecord_legacy_outlet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="county_fips",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="place",
            name="county_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="place",
            name="feature_class",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="place",
            name="state_fips",
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
    ]
