# Generated by Django 5.2.17 on 2026-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0003_place_county_fips_place_county_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="census_geoid",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name="place",
            name="census_geoid_source",
            field=models.CharField(
                blank=True, help_text="which gazetteer file it came from", max_length=32
            ),
        ),
    ]
