# Generated by Django 5.2.17 on 2026-08-19 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0004_place_census_geoid_place_census_geoid_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error — blocks publishing"),
                            ("warn", "Warning"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("message", models.TextField()),
                ("row_id", models.CharField(blank=True, max_length=64)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="directory.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "data quality issue",
                "ordering": ("severity", "rule"),
                "indexes": [
                    models.Index(
                        fields=["severity", "rule"],
                        name="directory_d_severit_6cbcdb_idx",
                    )
                ],
            },
        ),
    ]
